# This is the top-level playbook for deploying Bokeh at UNC

- hosts: all
  ansible_required: 1.9
  user: vagrant
  become: True
  become_user: root
  gather_facts: True
  vars_files:
      - vars/defaults.yml
      - vars/user.yml

  roles:
      - kohadevbox
